exclude_path = [
  "dataset/*.*",
  "report_template.html",
  "3W_DATASET_STRUCTURE\\.md$",
  "BACKLOG\\.md$",
]

accept = ["100..=103", "200..=299", "403", "406", "429"]

user_agent = "Mozilla/5.0"

# To prevent TLS certificate errors as in `certificate not valid for name "tbpetroleum.com.br"; certificate is only valid for DnsName("www.tbpetroleum.com.br")`
insecure = true

exclude = [
  '^https://prd\.hotsitespetrobras\.com\.br/en/contact-us/?$',
  '^http://doi\.org/10\.55905/ijsmtv10n4-041$',
  '^http://www\.fsma\.edu\.br/si/edicao28/FSMA_SI_2021_2_04_Varejao_Final\.pdf$',
  '^https://doi\.org/10\.48072/2525-7579\.rog\.2020\.405$',
  '^https://biblioteca\.ibp\.org\.br/scripts/bnmapi\.exe\?router=upload/33989$',
  '^https://doi\.org/10\.48072/2525-7579\.rog\.2022\.(298|307)$',
]