name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Check python code using the official black action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /*
            !*.parquet
          sparse-checkout-cone-mode: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: psf/black@stable
        with:
          src: "."
          options: "--check --verbose --diff"